export const PUT_INCOGNITO_MODE_REQUEST = 'PUT_INCOGNITO_MODE_REQUEST'
export const PUT_INCOGNITO_MODE_SUCCESS = 'PUT_INCOGNITO_MODE_SUCCESS'
export const PUT_INCOGNITO_MODE_FAIL = 'PUT_INCOGNITO_MODE_FAIL'

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL'

export const GET_NEAR_BY_USERS_REQUEST = 'GET_NEAR_BY_USERS_REQUEST'
export const GET_NEAR_BY_USERS_SUCCESS = 'GET_NEAR_BY_USERS_SUCCESS'
export const GET_NEAR_BY_USERS_FAIL = 'GET_NEAR_BY_USERS_FAIL'

export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL'

export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST'
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL'